runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /api/lab
  script: labv1.app
- url: /v2/api/lab
  script: labv2.app
- url: /lab
  static_dir: static
- url: /lab/css
  static_dir: static/css
- url: /api/ro
  script: ro.app
- url: /api/login
  script: login.app